name: final_project_csc464_p006
description: A Flutter app for course management
publish_to: 'none' # change if you plan to publish

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
<<<<<<< Updated upstream
    
  # adding provider
  provider: ^6.1.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # adding firebase and firestore
  firebase_core: 
  cloud_firestore:
=======
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  firebase_core: ^2.11.0
  cloud_firestore: ^4.8.0
>>>>>>> Stashed changes

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # If you have assets, list them here. Example:
  # assets:
  #   - assets/images/
